class Nmaahcmm < Formula
  desc "scripts for running NMAAHC microservices"
  homepage "https://github.com/NMAAHC/nmaahcmm"
  url "https://github.com/NMAAHC/nmaahcmm/archive/v0.0.2.tar.gz"
  sha256 "cca3b9417bc4fb854f5da794e1b64916b67c2e5856d578913e991d0de88c2927"
  head "https://github.com/NMAAHC/nmaahcmm.git"

  depends_on "cowsay"
  depends_on "dvdauthor"
  depends_on "dvdrtools"
  depends_on "exiftool"
  depends_on "ffmpeg" => ["with-sdl2", "with-freetype"]
  depends_on "flac"
  depends_on "md5deep"
  depends_on "media-info"
  depends_on "mediaconch"
  depends_on "normalize"
  depends_on "rsync"
  depends_on "sdl"
  depends_on "tree"
  depends_on "xmlstarlet"

def install
    bin.install "bashrc"
    bin.install "makeconcat"
    bin.install "diffFrameMD5"
    bin.install "makechecksum"
    bin.install "makeDer"
    bin.install "makedrivetree"
    bin.install "makeframemd5"
    bin.install "makeH264"
    bin.install "moveDPX"
    bin.install "nmaahcmmfunctions"
    bin.install "restructure"
    bin.install "restructureDER"
    bin.install "restructureDPX"
    bin.install "restructureForVFCU"
    bin.install "writemetadata"
  end
end
